name: Ubuntu Caller Workflow

on:
    workflow_dispatch

jobs:
    call_reusable_workflow:
        uses: jhartrallscripts/many_runners/.github/workflows/reusable_workflow.yml@main
        with:
            runner_type: ${{ matrix.runner_type }}
        strategy:
            matrix:
                runner_type: [ubuntu-latest, ubuntu-20.04, ubuntu-18.04]