name: Ubuntu Caller Workflow

on:
    push:
        branches:
            - main

jobs:
    call_reusable_workflow:
        uses: jhartrallscripts/many_runners/.github/workflows/reusable_workflow.yml@main
        with:
            runner_type: ${{ matrix.runner_type }}
            tagline: ${{ matrix.runner_label }}
        strategy:
            matrix:
                runner_type: [ubuntu-latest, ubuntu-20.04, ubuntu-22.04]
                include:
                    - runner_type: ubuntu-latest
                      runner_label: ubuntu-latest-and-greatest
                    - runner_type: ubuntu-20.04
                      runner_label: ubuntu-20.04-stable
                    - runner_type: ubuntu-22.04
                      runner_label: ubuntu-22.04-bleeding-edge